apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xbii
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-easy-tenant/rhtap-demo-app/hacbs-test-project-xbii@sha256:e86f76d4001405847d4258123ac47be33a23ad2bfcc1a0c432661752ad364e70
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
